development:
  GOOGLE_CLIENT_ID: 248094829883-gthts0sl7vcm1c0dl5vjhdkr1c35a8t3.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: zsKKsWOshzgyKVDo24jmjI1n
  TWITTER_CLIENT_ID: RXphrDprLTXnZMrl0WlUu4GcK
  TWITTER_CLIENT_SECRET: ueZFr4rUSRuoIUy2wotLNavqjLYo63ayGHm4plKVh4TGka978d
  YAHOO_CLIENT_ID: dj0yJmk9SVNONE1JYXFZamJVJmQ9WVdrOWNIaGthbEF4TTJNbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1mOA--
  YAHOO_CLIENT_SECRET: fc1225d4430209584ceed63427faa216aa3fea5a
test:
  GOOGLE_CLIENT_ID: 248094829883-gthts0sl7vcm1c0dl5vjhdkr1c35a8t3.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: zsKKsWOshzgyKVDo24jmjI1n
  TWITTER_CLIENT_ID: RXphrDprLTXnZMrl0WlUu4GcK
  TWITTER_CLIENT_SECRET: ueZFr4rUSRuoIUy2wotLNavqjLYo63ayGHm4plKVh4TGka978d
  YAHOO_CLIENT_ID: dj0yJmk9SVNONE1JYXFZamJVJmQ9WVdrOWNIaGthbEF4TTJNbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1mOA--
  YAHOO_CLIENT_SECRET: fc1225d4430209584ceed63427faa216aa3fea5a
production:
  GOOGLE_CLIENT_ID: XXX
  GOOGLE_CLIENT_SECRET: XXX
  TWITTER_CLIENT_ID: XXX
  TWITTER_CLIENT_SECRET: XXX
  YAHOO_CLIENT_ID: XXX
  YAHOO_CLIENT_SECRET: XXX
  SECRET_KEY_BASE: XXX
  DEVISE_KEY_SECRET: XXX
