# default config
defaults: &defaults
  adapter:  active_record
  language: en
  writer:   direct

development:
  database: db/xapian_db/development
  <<: *defaults

test:
  database: ":memory:"
  <<: *defaults


production:
  database:     db/xapian_db/production
  writer:       resque
  resque_queue: my_queue
  <<: *defaults

# production:
#   # Make sure the beanstalk daemon and the beanstalk worker are running
#   database: db/xapian_db/production
#   # writer:   beanstalk
#   # beanstalk_daemon: localhost:11300
#   <<: *defaults